### ISSUE TITLE
bintrayUpload fails on travis-ci for some mysterious reason

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/jpl.imce.oml.specification.parent#1]
It is baffling that it is so difficult to get some insight why upload is rejected with 401:

https://travis-ci.org/JPL-IMCE/jpl.imce.oml.specification.parent/builds/197042630#L4661

```
Gradle Bintray Plugin version: 1.7.3
Version 'jpl-imce/gov.nasa.jpl.imce.p2/jpl.imce.oml.specification.p2/0.2.0' does not exist. Attempting to create it...
:jpl.imce.oml.specification.repository:bintrayUpload FAILED
:jpl.imce.oml.specification.repository:bintrayUpload (Thread[main,5,main]) completed. Took 1.402 secs.
```

The stack trace clearly points to the [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin):

https://travis-ci.org/JPL-IMCE/jpl.imce.oml.specification.parent/builds/197042630#L4738

```
Caused by: org.gradle.api.GradleException: Could not create version '0.2.0': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure6_closure28_closure32.doCall(BintrayUploadTask.groovy:323)
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
```

The source code is here:
https://github.com/bintray/gradle-bintray-plugin/blob/master/src/main/groovy/com/jfrog/bintray/gradle/BintrayUploadTask.groovy#L223

**Comment by NicolasRouquette** [comment]
The credentials were incorrectly configured on travis.
